server:
  port: 9009
spring:
  application:
    name: tensquare‐sms #指定服务名
  rabbitmq:
    host: 192.168.220.130
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true