server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.220.130:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: 369369
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true