server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.220.130:3306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: 369369
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.220.130
